user_name = $(shell whoami)
# Only need to change if you install boost-python from source
OPENCV = /Users/$(user_name)/opt/anaconda3/envs/py39/include/opencv4/
# -I$(OPENCV)
main:
	g++ -std=c++14 -I$(OPENCV) main.cpp

#-I /Users/maruyama/opt/anaconda3/envs/py39/include/opencv4/

# 天才 http://omilab.naist.jp/~mukaigawa/misc/Makefile.html